### ISSUE TITLE
Implement a simple Crowdfunding contract example 

### ISSUE THREAD

**Issue by coxmars** [KaizeNodeLabs/stark-cairo-nodes#60] opened 2024-12-11 14:46 UTC
# Implement Simple Crowdfunding System

## Objective
Create a contract that allows users to raise funds for a project with a target amount and deadline.

## Basic Features
- Create campaign with funding goal and deadline
- Allow contributions
- Automatically end campaign at deadline
- Return funds if goal is not met
- Transfer funds to creator if goal is met

## Technical Considerations
- Safe timestamp handling
- Automatic refund system
- Track contributions per address
- Campaign states (Active, Successful, Failed)

## Documentation
- https://starknet-by-example.voyager.online/applications/crowdfunding

## 📜 Additional Notes
⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by bloomingpeach** [comment] 2024-12-12 14:00
Hi, can I work on this issue @coxmars, I have experience in Cairo and worked on various projects(Shinigami, Art-peace,...)

**Comment by aradix16** [comment] 2024-12-12 14:02
Hi ! I've already contributed to this project during ODHack10 and would love to keep learning Cairo by working on this issue.
During ODHack, I implemented a fibonacci example in Cairo and also coded an ERC721 contract for another project, so I'm confident I could implement this crowdfunding contract in a few days.
Thanks!

**Comment by anonfedora** [comment] 2024-12-12 14:03
I'm Anonfedora, a full stack Blockchain developer (Backend heavy)...
1. Campaign Structure: Define a struct to store campaign details (creator, funding goal, deadline, contributions, and state). 
2. Create Campaign: Implement a function to initialize campaigns with a funding goal, deadline, and creator address. 
3. Contribute: Allow users to send funds, track contributions per address, and update the campaign's total funds. 
4. End Campaign: Implement a function to check the deadline, mark campaigns as successful/failed, and handle fund transfers or refunds. 
5. State and Safety: Use enums for campaign states, and ensure secure handling of timestamps and fund transfers using checks and safe math practices and write unit tests for the functions.
ETA: 72 HOURS

**Comment by manlikeHB** [comment] 2024-12-12 14:13
Hi, I am a returning contributor and a Cairo Developer with great experience contributing to lots of amazing Cairo projects. can I work on this?

**Comment by jaiminRaiyani** [comment] 2024-12-12 14:16
Would love to tackle this!

**Comment by greatest0falltime** [comment] 2024-12-12 14:17
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by beeguy74** [comment] 2024-12-12 14:42
Hi, I am a beginner Cairo developer from Paris.
I closed one task on 10 ODHACK for ByteBeasts.
I will check the existing ERC crowdfunding smart-contracts to implement a robust version of the  contract for you.
I don't promise to finish the issue quickly because your project is new to me =)
But I intend to do a decent job and at least do the draft PR within 48 hours.
Could I try solving this?

**Comment by BrunoAmbricca** [comment] 2024-12-12 14:43
I would like to work on this issue

**Comment by jimenezz22** [comment] 2024-12-12 14:49
Hi, I’d like to work on this issue! I’m member of Dojo Coding Community and I have extensive experience working with Cairo, including contributions to projects like **CairoLint**, utilizing **Dojo Engine** to create on-chain games at **ByteBuilders**, completing Cairo-based quests with **Node Guardians**, and teaching a Cairo class at a **Starknet bootcamp**

### My Approach:

1. **Campaign Creation**
    - Implement a function to create campaigns with parameters for the funding goal and deadline.
    - Store essential details such as the campaign creator, target amount, deadline, and initial state (`Active`).
2. **Contributions**
    - Add a function to allow users to contribute to a campaign.
    - Track contributions by address using a mapping, ensuring each contributor's balance is updated accurately.
    - Update the total amount pledged after each contribution.
3. **Campaign End**
    - Implement logic to automatically evaluate the campaign state at the deadline:
        - **Successful:** If the goal is met, transfer the funds to the campaign creator and update the state to `Successful`.
        - **Failed:** If the goal is not met, update the state to `Failed` and allow contributors to claim refunds.
4. **Refunds**
    - Create a function to enable contributors to withdraw their pledged funds if the campaign is in the `Failed` state.
    - Ensure refunds are processed safely and the contributor's balance is reset after withdrawal.
5. **Technical Considerations**
    - Use Cairo's native time handling for accurate and safe deadline management.
    - Introduce events to log key actions (e.g., contributions, refunds, campaign success).
    - Ensure gas efficiency and safe interaction patterns by designing the contract logic to minimize state reads/writes.

### Additional Value:

I will also write a comprehensive suite of tests to validate all functionalities of the contract, covering both unit and integration tests. This will ensure the contract operates as intended under various scenarios, including edge cases.

ETA: 3 days maximum in the worst case scenario.

**Comment by wheval** [comment] 2024-12-12 14:51
May I be assigned to this?

**Comment by 1nonlypiece** [comment] 2024-12-12 14:51
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by NueloSE** [comment] 2024-12-12 15:03
May I take care of this?

**Comment by mimiprosper** [comment] 2024-12-12 15:06
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. 
If assigned this i would complete it within 2 days. 

Here are some articles i have written: https://medium.com/@emma.onyedika.okeke

**Comment by casweeney** [comment] 2024-12-12 15:07
# I have supper experience with Crowd funding smart contracts.

## About me:
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.

## Tackling this issue:
- I will scaffold a new project then I will set up the interfaces
- I will create a struct `Campaign` that holds all the campaign properties.
- I will create all necessary functions as specified above as entry points to interact with the campaign contract.

## ETA: 10 - 12 hours max

**Comment by GideonBature** [comment] 2024-12-12 15:11
May I be assigned to this?

My name is Gideon Bature, a Software Engineer, I have experience working with Cairo, I have written various contracts on Starknet using Cairo. If given the opportunity, I will send my first PR within 72 hours.

Thank you!

**Comment by Supa-mega** [comment] 2024-12-12 15:12
Can I handle this task?

**Comment by 3th-Enjay** [comment] 2024-12-12 15:12
I’d like to work on this.

**Comment by zintarh** [comment] 2024-12-12 15:12
Can I handle this task?

**Comment by beeguy74** [comment] 2024-12-12 15:13
Hi, I am a beginner Cairo developer from Paris.
I closed one task on 10 ODHACK for ByteBeasts.
I will check the existing ERC crowdfunding smart-contracts to implement a robust version of the  contract for you.
I don't promise to finish the issue quickly because your project is new to me =)
But I intend to do a decent job and at least do the draft PR within 48 hours.
Could I try solving this?

**Comment by ryzen-xp** [comment] 2024-12-12 15:14
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects ,sunshine lab etc.
I can implement the Simple Crowdfunding contract, ensuring all basic features like campaign creation, contributions, automatic deadline handling, and fund transfers or refunds. Please assign this issue to me.

Thank you!

**Comment by Akshola00** [comment] 2024-12-12 15:14
Hello, I'm Akinshola Akinniyi, a smart contract developer with expertise in StarkNet and Cairo. After completing the Cairo Basecamp, I gained a strong understanding of decentralized applications and have contributed to multiple projects on OnlyDust, focusing on smart contract development and optimization.

I would love to take on the task of implementing a simple crowdfunding system. With my experience in developing smart contracts, I am confident in creating a contract that handles campaign creation, contributions, automatic deadline management, and funds transfer or refund, ensuring the system works smoothly. Please assign me this task—I look forward to contributing to the project!

**Comment by trashcancries** [comment] 2024-12-12 15:28
May I work on this issue @danielcdz?

eta: 3 days

**Comment by ShantelPeters** [comment] 2024-12-12 15:47
Mind if I take this issue?

**Comment by omsant02** [comment] 2024-12-12 17:25
i would like to take this issue

Here's my implementation plan:

-Create a simplified version of the Campaign struct with essential fields (creator, 
  goal, deadline, token address, pledges tracking)
-Implement main functions based on the reference implementation: pledge(), 
 unpledge(), claim(), and refund()
-Add state management (Active/Successful/Failed) using get_block_timestamp()
-Use ERC20 token integration for handling contributions
-Implement pledge tracking using similar but simplified storage pattern from the 
  reference

I'll keep it educational by removing complex features like upgradability and components, while maintaining core functionality and proper security checks. I'll also provide documentation following starknet-by-example's format.

**Comment by Bosun-Josh121** [comment] 2024-12-12 17:35
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged:

software engineering background, backend & smart contract dev with contributions on OD(https://app.onlydust.com/u/Bosun-Josh121) looking to make first contribution on this project

How I plan on tackling this issue:
accept contributions, track donations by address, automatically close campaigns at the deadline, refund contributors if the goal is not met, and transfer funds to the campaign creator if the target is achieved, ensuring secure timestamp handling and reliable state management as outlined in StarkNet by Example: Crowdfunding.

work on feedback & recommendation ensuring contact. Can deliver within a day upon assignment

**Comment by Jagadeeshftw** [comment] 2024-12-12 17:54
Hello @coxmars ,

I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet.


My Approach:

1. I’ll implement a simple crowdfunding contract that allows users to create campaigns with a funding goal and deadline. 
2. The contract will allow contributions, handle automatic refunds if the goal is not met, and transfer funds to the creator if the goal is achieved, tracking contributions by address.

Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by tasneemtoolba** [comment] 2024-12-12 21:23
I'm a full-stack developer who recently shifted to web3, and trying so hard to gain experience in smart contracts!! I do a small experience writing smart contracts in Solidity and Cairo!, looking forward to work on this task!!

**Comment by ikezuby2012** [comment] 2024-12-12 21:52
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Express.js, and recently exploring Cairo for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to take this issue

**Comment by suhas-sensei** [comment] 2024-12-12 21:59
Could I try solving this? I'll implement a Starknet crowdfunding contract with secure funds management, deadline tracking, and automatic refund logic.
 Having experience with Starknet development and financial contracts, I'll ensure proper state transitions and contribution tracking while implementing comprehensive refund mechanisms.
ETA : 48-70hrs

**Comment by nonso7** [comment] 2024-12-12 22:58
I am very confident building this type of contracts. Can I attempt this issue?

**Comment by michojekunle** [comment] 2024-12-13 01:04
Could I try solving this?

**Comment by Birdmannn** [comment] 2024-12-13 04:32
Hi Dev, can I handle this task?

**Comment by Nityam573** [comment] 2024-12-13 05:08
Could I try solving this?

**Comment by 0xprivateChaos** [comment] 2024-12-13 05:41
Hi, I'm Aman, and I'd like to work on this issue.

My plan:

1. Implement `create_campaign()` for users to set funding goals and deadlines.
2. Add `contribute()` to track contributions per address.
3. Handle campaign states (Active, Successful, Failed) based on deadlines and funding goals.
4. Create `refund()` for contributors if the goal is unmet and `withdraw()` for creators if successful.
5. Ensure safe timestamp handling and robust access control.

**Comment by Emmanex01** [comment] 2024-12-13 07:41
Could I try solving this?

**Comment by savagechucks** [comment] 2024-12-13 07:49
Yo, my name's Isaac. I'm a frontend dev. I'm a new contributor... I'd appreciate it if I'd be given the chance to try out this issue
ETA: 2days

**Comment by olisaagbafor** [comment] 2024-12-13 10:24
May I take care of this?

**Comment by Dorcas18** [comment] 2024-12-13 12:08
I’m interested in this one.

**Comment by DADADAVE80** [comment] 2024-12-13 12:11
Can I handle this task?

**Comment by Pvsaint** [comment] 2024-12-13 12:47
Could I grab this task? I'm a front-end and smart contract developer proficient in react js, next js, solidity and cairo

**Comment by sandragcarrillo** [comment] 2024-12-13 15:06
Hi, I would love to get assigned to this issue. 

I have been learning Cairo for the past 4 months, learning while writing technical content useful for other new devs. This would be an amazing opportunity to keep improving my skills. 

ETA: 1-2 days

**Closed** 2024-12-23 02:33 UTC
Labels: enhancement, difficult: medium, ODHack11
