### ISSUE TITLE
Create a simple ERC721 contract

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#31] opened 2024-11-21 10:20 UTC
## Description
- As part of the examples, we aim to include an ERC721 contract to explore its structure and gain a fundamental understanding of token standards, including how they operate and interact within the blockchain ecosystem.

## Steps
- Add a new ERC721 contract in the corresponding directory.

**Comment by mayasimi** [comment] 2024-11-21 14:06
Is it okay if I take this?

**Comment by SoarinSkySagar** [comment] 2024-11-21 14:08
May I work on this issue @danielcdz?

My approach: I would use the OpenZeppelin/cairo-contracts to create a new EC 721 contract, and write extensive tests for the contract, then ensure that every test is passing before making the PR

ETA: 2 days

**Comment by omsant02** [comment] 2024-11-21 14:09
I’m interested in this one.

**Comment by raizo07** [comment] 2024-11-21 14:10
Could I grab this task? I'm a software developer with over four years experience.

I'll ERC721 contract with appropriate test to go along with it

ETA: 10 hours

**Comment by codeZe-us** [comment] 2024-11-21 14:11
Mind if I take this issue?
ETA: 5 hours

**Comment by rogeralbp** [comment] 2024-11-21 14:12
Hi team! I'm part of the Dojo Coding I would like to participate in this issue  to practice my Cairo Skills, would  love to start my journey on Open Source with you guys

**Comment by manlikeHB** [comment] 2024-11-21 14:24
Hi, I am a Cairo developer with great experience contributing to lots of Cairo code base. I would love to work on creating the erc-721(NFT) contract.

**Comment by mimisavage** [comment] 2024-11-21 14:27
I'd be happy to do this.

**Comment by ShantelPeters** [comment] 2024-11-21 14:35
Can I try solving this issue?
To solve this issue,  I will create a new ERC721 contract in the specified directory. Next i will implement the basic ERC721 standard, including functionalities for minting, transferring, and querying token ownership.
Also i will  ensure the contract follows the ERC721 specification, adhering to functions like balanceOf, ownerOf, and transferFrom.
Lastly is to include events like Transfer and Approval for standard compliance.

**Comment by Unickhub** [comment] 2024-11-21 14:37
Let me try this one!

**Comment by Benjtalkshow** [comment] 2024-11-21 14:47
I’m interested in this one.

**Comment by NueloSE** [comment] 2024-11-21 15:07
Can I take this from here?

**Comment by MullerTheScientist** [comment] 2024-11-21 15:31
can i please address this task

**Comment by ryzen-xp** [comment] 2024-11-21 15:32
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I am expert in ERC721  contract  development   .   please /assign  this issue .
Thank You

**Comment by MrRoudyk** [comment] 2024-11-21 15:35
Let me handle this issue!

**Comment by Michaelkingsdev** [comment] 2024-11-21 15:39
I'd be happy to do this.

**Comment by casweeney** [comment] 2024-11-21 15:43
## About me:
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.


## Tackling this issue:
- I will create an ERC721 smart contract that implements the Openzeppelin ERC721 component.
- In the ER721 implementation I will use the MixinImlp from Openzeppelin.

**Comment by mimiprosper** [comment] 2024-11-21 16:06
Could I try solving this?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 1 day.

**Comment by ryzen-x** [comment] 2024-11-21 16:15
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by rogeralbp** [comment] 2024-11-21 20:07
Thank you for assigning me the issue. I am working on it right now.

**Comment by rogeralbp** [comment] 2024-11-21 21:22
my ETA for the issue is 2 Days

**Comment by rogeralbp** [comment] 2024-11-22 19:16
I get stuck with the dependencies part and also in the deployment of the Contract, also I had a late thing from work, I could not finish. Next issue will be re-prepared with this steps

**Comment by SoarinSkySagar** [comment] 2024-11-22 19:21
May I work on this issue @danielcdz? 

I am a cairo dev with extensive experience in building on cairo and also a regular contributor at @keep-starknet-strange and the starknet ecosystem in general. You can see my PoW on my github and onlydust profile.

my approach: I will utilize OpenZeppelin/cairo-contracts repo to create the ERC 721 contract, and make sure it is running as expected and also maintain code cleanliness using scarb fmt command.

eta: 1 day

**Comment by casweeney** [comment] 2024-11-22 19:57
> ## About me:
> I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking
> 
> I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.
> 
> Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.
> 
> ## Tackling this issue:
> * I will create an ERC721 smart contract that implements the Openzeppelin ERC721 component.
> * In the ER721 implementation I will use the MixinImlp from Openzeppelin.

@danielcdz can I work on this, I will deliver this in 5 hours. Checkout my repo: https://github.com/casweeney/awesome-starknet-cairo, where I have implemented a lot of contracts.

**Comment by saimeunt** [comment] 2024-11-22 20:21
Hey, I have past experiences using Cairo NFT contracts such as https://github.com/carbonable-labs/cairo-erc-7498
I will implement either an ERC721 contract from scratch or using OpenZeppelin and provide accompanying tests to showcase the interface.

**Comment by baitcode** [comment] 2024-11-22 20:51
Background: https://nodeguardians.io/campaigns/entering-cairo
I've experiennce creating ERC20 and ERC721 and happy to do that again.

**Comment by josephpdf** [comment] 2024-11-22 22:28
Hi! @danielcdz 
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Understand the Requirements:** Review the ERC721 token standard and its structure to ensure compliance.
2. **Create the Contract:** Implement the ERC721 contract in the designated directory, focusing on clarity and simplicity to facilitate understanding for users.
3. **Include Documentation:** Provide comments and documentation within the contract to explain key functionalities.
4. **Testing:** Write tests to validate the behavior of the contract.
5. **Review and Submit:** Submit the implementation via a pull request for review.

**Comment by petersdt** [comment] 2024-11-23 02:19
Is this issue still available?

kindly assign me 

am a frontend developer with some level of experience in writing and testing smart contracts

**Comment by NueloSE** [comment] 2024-11-23 02:23
@danielcdz I a developer and I worked on implementing ERC20 token before. kindly assign me this task of implementing ERC721(NFT)

**Comment by Aditya-040** [comment] 2024-11-23 05:15
Can I attempt this issue?

**Closed** 2024-11-25 19:40 UTC
Labels: ODHack10, difficult: easy, starknet-contract
