### ISSUE TITLE
Fix templates not rendering for issues and PRs

### ISSUE THREAD

**Issue by danielcdz** [KaizeNodeLabs/stark-cairo-nodes#70] opened 2024-12-11 19:12 UTC
## 📄 Description  
- Our repository includes templates designed to render when creating new issues or opening pull requests (PRs). However, these templates are currently not rendering as expected. This issue is likely related to the location of the `.md` files.  
- The objective is to investigate the root cause of this problem and submit a PR with the necessary fixes to restore proper functionality.  

## ✅ Acceptance Criteria  
- Issue and PR templates render correctly when creating new issues or pull requests.  
- The solution is implemented and documented through a merged PR.  

## 📜 Additional Notes
⚠ **Do not apply until the ODHack begins.**
⚠ **Read our guidelines before applying.**

**Comment by greatest0falltime** [comment] 2024-12-12 14:16
Hi,  

I’d be thrilled to work on this issue as I have extensive experience with Cairo programming and building decentralized applications on StarkNet.  

ETA:  
I expect to have a working solution ready within the next 24 hours. Kindly let me know if I can proceed!   

Looking forward to contributing!

**Comment by BrunoAmbricca** [comment] 2024-12-12 14:41
I would like to work on this issue

**Comment by Kingsuite** [comment] 2024-12-12 14:51
Can I work on this, please?

**Comment by 1nonlypiece** [comment] 2024-12-12 14:51
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by Michaelkingsdev** [comment] 2024-12-12 15:11
I’d like to resolve this.

**Comment by abdegenius** [comment] 2024-12-12 15:12
Could I try solving this?

**Comment by 3th-Enjay** [comment] 2024-12-12 15:12
Mind if I try this one?

**Comment by Supa-mega** [comment] 2024-12-12 15:13
Let me handle this issue!

**Comment by Akshola00** [comment] 2024-12-12 15:14
can i work on this 
im confident I can handle this 
I'm Akinshola a dev and I've worked with github for long
I'm confident I can work on this issue 
eta 1 day

**Comment by GideonBature** [comment] 2024-12-12 15:15
I’m interested in this one.

**Comment by zanastas** [comment] 2024-12-12 15:15
I have read through the documentation and I am confident that I can fix this issue 😊

**Comment by SimplementeCao** [comment] 2024-12-12 15:27
---

### Hey! I'm *SimplementeCao*. 👋

I have contributed before to other projects like:

- `Cairo Book`
- `Starknet Book`
- `Starknet Docs`
- `Starknet Security Challenges Factory`
- `Starkane`

Can I work on this issue?

Check my OnlyDust, I've contributed to many projects: [OnlyDust Profile](https://app.onlydust.com/u/SimplementeCao), 
and my [GitHub](https://github.com/SimplementeCao)

---

### Plan to Solve the Issue:

1. **Analyze the codebase** to understand the current structure and functionality.
2. **Review the problem description** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I face any challenge, I will **ask questions promptly** in the relevant support group or communication channel to move forward efficiently.
5. Once resolved, I will **open a PR** and wait for your feedback.

---

Let me know if I can start working on this! 🚀

---

**Comment by tasneemtoolba** [comment] 2024-12-12 15:35
Mind if I take this issue?  I'm from the community chat! looking forward to contribute futher on this project!

**Comment by omsant02** [comment] 2024-12-12 17:07
I would like to take this issue

I've identified that the templates are missing the required YAML frontmatter, which is why they're not rendering properly. I'll create a PR that adds the correct frontmatter structure to both the issue and PR templates

ETA : 5 hrs

**Comment by Jagadeeshftw** [comment] 2024-12-12 17:48
Hello, I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by salazarsebas** [comment] 2024-12-12 18:58
Hi stark-cairn-nodes,

# My background

I'm Sebastian, software engineer 👨🏻‍💻 and part of the Dojo Coding ⛩️ community, and I would like to contribute to this issue. I have experience with different technologies and I have worked on some projects through OnlyDust and I like to contribute to help the projects.

# How I plan on tackling this issue
To solve this issue, I will perform the following steps:
- Modify in the .github folder to display the templates as required.
- Fix the cause that does not allow issue and pr templates to be displayed.
- Verify that the tests are working correctly.
- Send a pr pending feedback.

**Comment by SimplementeCao** [comment] 2024-12-12 19:14
Hi, I'm Leandro, Front-end developer.
I would solve the issue first by reviewing the code and fix the bug that does not allow the correct display of the template.
Estimated delivery time: 20 hours.

I have previously collaborated on other projects such as:

Cairo Book
Starknet Book
Starknet Docs
Starknet Security Challenge Factory
Starkane
Can I work on this topic?

Check out my OnlyDust, I have contributed to many projects: OnlyDust profile,
and my GitHub

**Comment by Yunusabdul38** [comment] 2024-12-12 21:01
Can I take this issue?

**Comment by od-hunter** [comment] 2024-12-12 21:31
Could I take a shot at this?Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

**Closed** 2024-12-15 03:00 UTC
Labels: bug, difficult: easy, ODHack11
